In [1]:
##1. Create a 4x4 matrix with values ranging from 0 to 3.
import numpy as np

x = np.zeros((4,4))
x += np.arange(4)
x

array([[0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.]])

In [2]:
#2. Create an array with shape of 4x4 and turn it into two arrays along the second axis
ar = np.arange(0,16)
ar = ar.reshape(4,4)
ar

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [6]:
ar1 = np.hsplit(ar, 2)
ar1

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]